### ISSUE TITLE
time-out in validation during initialization of Qowaiv.HouseNumber

### ISSUE THREAD

**Issue by roozemond** [Qowaiv/Qowaiv#263]
On multiple machines: 
Error of type:

```
System.TypeInitializationException: The type initializer for 'Qowaiv.HouseNumber' threw an exception. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: matchTimeout
   at System.Text.RegularExpressions.Regex.ValidateMatchTimeout(TimeSpan matchTimeout)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout)
   at Qowaiv.HouseNumber..cctor()
```

**Comment by Corniel** [comment]
Fixed with https://www.nuget.org/packages/Qowaiv/6.3.1
